import 'dart:typed_data';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../../core/fast_ai_service.dart';
import '../../core/vision_service.dart';
import '../../core/grades.dart';
import '../../theme/jagx_theme.dart';

class NexusChatScreen extends StatefulWidget {
  final Grade grade;
  final ValueChanged<Grade> onGradeChanged;
  const NexusChatScreen({super.key, required this.grade, required this.onGradeChanged});
  @override State<NexusChatScreen> createState() => _NexusChatScreenState();
}

class _Attachment { final String name; final String mime; final Uint8List bytes; const _Attachment(this.name,this.mime,this.bytes); }

class _NexusChatScreenState extends State<NexusChatScreen> {
  final controller = TextEditingController();
  final messages = <Map<String,dynamic>>[];
  final attachments = <_Attachment>[];
  bool busy = false;
  String status = '';
  @override void dispose(){controller.dispose();super.dispose();}

  String mime(String name){
    final e=name.split('.').last.toLowerCase();
    const m={'png':'image/png','jpg':'image/jpeg','jpeg':'image/jpeg','webp':'image/webp','gif':'image/gif','pdf':'application/pdf','txt':'text/plain','md':'text/markdown','json':'application/json','csv':'text/csv'};
    return m[e]??'application/octet-stream';
  }

  Future<void> pick() async {
    final r=await FilePicker.platform.pickFiles(allowMultiple:true,withData:true);
    if(r==null||!mounted)return;
    setState((){for(final f in r.files){if(f.bytes!=null)attachments.add(_Attachment(f.name,mime(f.name),f.bytes!));}});
  }

  Future<void> send() async {
    final text=controller.text.trim();
    if((text.isEmpty&&attachments.isEmpty)||busy)return;
    final files=List<_Attachment>.from(attachments);
    final oldHistory=messages.where((m)=>m['role']=='user'||m['role']=='assistant').map<Map<String,String>>((m)=>{'role':m['role'] as String,'content':m['content'] as String}).toList();
    controller.clear(); attachments.clear();
    setState((){messages.add({'role':'user','content':text.isEmpty?'Inspect the attached files.':text,'files':files});busy=true;status='Working…';});
    try {
      final image=files.where((f)=>f.mime.startsWith('image/')).firstOrNull;
      if(image!=null){
        status='Reading the image…';
        if(mounted)setState((){});
        final answer=await VisionService.analyze(bytes:image.bytes,mime:image.mime,prompt:text.isEmpty?'Read and explain this image in detail, including visible text.':text);
        if(!mounted)return;
        setState((){messages.add({'role':'assistant','content':answer,'model':'Vision'});busy=false;status='';});
        return;
      }
      final context=files.map((f){
        if(f.mime.startsWith('text/')||f.mime=='application/json'||f.mime=='text/csv')return '\nFILE ${f.name}:\n${String.fromCharCodes(f.bytes)}';
        return '\nATTACHED FILE: ${f.name} (${f.mime})';
      }).join();
      final result=await FastAiService.complete(message:'${text.isEmpty?'Inspect the attached files.':text}$context',history:oldHistory,coding:_isCoding,onProgress:(s){if(mounted)setState(()=>status=s);});
      if(!mounted)return;
      setState((){messages.add({'role':'assistant','content':result.text,'model':'${result.provider} • ${result.model}'});busy=false;status='';});
    }catch(e){if(!mounted)return;setState((){messages.add({'role':'assistant','content':'I could not complete that request.\n\n$e'});busy=false;status='';});}
  }

  bool get _isCoding=>widget.grade.id=='engineer'||widget.grade.id=='operator'||widget.grade.id=='coder-fast';

  Future<void> saveGenerated(Uint8List bytes) async {
    final dir=await getApplicationDocumentsDirectory();
    final file=File('${dir.path}/jagx-generated-${DateTime.now().millisecondsSinceEpoch}.png');
    await file.writeAsBytes(bytes);
    await Share.shareXFiles([XFile(file.path)],text:'Generated by JagX AI');
  }

  void modes(){showModalBottomSheet<void>(context:context,backgroundColor:JagxColors.surface,builder:(_)=>ListView(padding:const EdgeInsets.all(18),children:[const Text('AI modes',style:TextStyle(color:JagxColors.fg,fontSize:22,fontWeight:FontWeight.w700)),...grades.map((g)=>ListTile(title:Text(g.label,style:const TextStyle(color:JagxColors.fg)),subtitle:Text(g.blurb,style:const TextStyle(color:JagxColors.muted)),trailing:g.id==widget.grade.id?const Icon(Icons.check,color:JagxColors.accent):null,onTap:(){Navigator.pop(context);widget.onGradeChanged(g);}))]));}

  @override Widget build(BuildContext context){return Column(children:[Expanded(child:messages.isEmpty?const SizedBox.expand():ListView.builder(padding:const EdgeInsets.all(18),itemCount:messages.length,itemBuilder:(context,i){final m=messages[i];final user=m['role']=='user';final files=(m['files'] as List<_Attachment>?)??const <_Attachment>[];return Padding(padding:const EdgeInsets.only(bottom:18),child:Align(alignment:user?Alignment.centerRight:Alignment.centerLeft,child:Container(constraints:const BoxConstraints(maxWidth:680),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:user?JagxColors.elevated:Colors.transparent,borderRadius:BorderRadius.circular(18)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[if(user&&files.isNotEmpty)Text('${files.length} attachment(s)',style:const TextStyle(color:JagxColors.muted,fontSize:11)),if(!user&&m['model']!=null)Text(m['model'] as String,style:const TextStyle(color:JagxColors.subtle,fontSize:10)),SelectableText(m['content'] as String,style:const TextStyle(color:JagxColors.fg,height:1.5)),if(m['imageBytes'] is Uint8List)Padding(padding:const EdgeInsets.only(top:10),child:Image.memory(m['imageBytes'] as Uint8List)),if(m['imagePath'] is String)Padding(padding:const EdgeInsets.only(top:8),child:TextButton.icon(onPressed:()=>saveGenerated(File(m['imagePath'] as String).readAsBytesSync()),icon:const Icon(Icons.download),label:const Text('Save / share image')))]))));})),if(busy)Padding(padding:const EdgeInsets.only(bottom:6),child:Text(status.isEmpty?'Working…':status,style:const TextStyle(color:JagxColors.muted,fontSize:12))),if(attachments.isNotEmpty)SizedBox(height:42,child:ListView(scrollDirection:Axis.horizontal,children:attachments.map((a)=>Padding(padding:const EdgeInsets.only(right:6),child:Chip(label:Text(a.name,maxLines:1,overflow:TextOverflow.ellipsis),onDeleted:busy?null:()=>setState(()=>attachments.remove(a)))).toList())),SafeArea(top:false,child:Padding(padding:const EdgeInsets.fromLTRB(12,4,12,12),child:Container(padding:const EdgeInsets.symmetric(horizontal:6),decoration:BoxDecoration(color:JagxColors.surface,borderRadius:BorderRadius.circular(24),border:Border.all(color:JagxColors.elevated)),child:Row(children:[IconButton(onPressed:busy?null:pick,icon:const Icon(Icons.add_circle_outline,color:JagxColors.fg)),IconButton(onPressed:busy?null:modes,icon:const Icon(Icons.tune,color:JagxColors.muted)),Expanded(child:TextField(controller:controller,minLines:1,maxLines:7,decoration:const InputDecoration(hintText:'Message',border:InputBorder.none),onSubmitted:(_)=>send())),IconButton.filled(onPressed:busy?null:send,icon:busy?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.arrow_upward))]))))]);}
}
